services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: smartcafe
      POSTGRES_PASSWORD: smartcafe
      POSTGRES_DB: smartcafe
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8088:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
